### PR TITLE
Update mania.txt

### PR DESCRIPTION
**Pull request by YoshiAye**
added 12k
mistake
P 12 KeyImage10D mania-key2D png
P 12 KeyImage10D mania-key1D png
should be
P 12 KeyImage10D mania-key2D png
P 12 KeyImage11D mania-key1D png

### CODE REVIEW

**Review by RoanH — DISMISSED** [review]
Hey,

Thank you for taking the time to add this. 

I am going to raise the key limit and also go ahead and add 14K, 16K and 18K in order to completely reflect all the options. I'm not sure when exactly I'll merge in these changes, but they'll be released with version 2.2.

I also noticed that the number of mania tabs is really getting quite annoying to navigate. So I might try to merge some of them into a single tab.

**Comment by YoshiAye** [comment]
In this holidays I'll write more I'm just not every day at home

**Comment by RoanH** [comment]
Awesome, I'll wait with any releases then.

Do you already know what you'll be working on, so that I don't end up working on the same things?

**Comment by YoshiAye** [comment]
I'll just finish 14 16 18 keys

**Comment by RoanH** [comment]
Ok, awesome. Thank you for helping out!

**Review by RoanH — APPROVED** [review]

**Comment by RoanH** [comment]
Apologies for the very late merge..., but it'll be in the next release. Thanks again for helping out.

**Pull request merged**
